// Code generated by MockGen. DO NOT EDIT.
// Source: categories_repository.go
//
// Generated by this command:
//
//	mockgen -source=categories_repository.go -destination=mocks/categories_repository_mock.go -package=models_mocks
//

// Package models_mocks is a generated GoMock package.
package models_mocks

import (
	reflect "reflect"

	models "github.com/mytheresa/go-hiring-challenge/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoriesRepositoryInterface is a mock of CategoriesRepositoryInterface interface.
type MockCategoriesRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCategoriesRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockCategoriesRepositoryInterfaceMockRecorder is the mock recorder for MockCategoriesRepositoryInterface.
type MockCategoriesRepositoryInterfaceMockRecorder struct {
	mock *MockCategoriesRepositoryInterface
}

// NewMockCategoriesRepositoryInterface creates a new mock instance.
func NewMockCategoriesRepositoryInterface(ctrl *gomock.Controller) *MockCategoriesRepositoryInterface {
	mock := &MockCategoriesRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockCategoriesRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoriesRepositoryInterface) EXPECT() *MockCategoriesRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCategoriesRepositoryInterface) Create(dto models.CategoryDto) (models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", dto)
	ret0, _ := ret[0].(models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCategoriesRepositoryInterfaceMockRecorder) Create(dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCategoriesRepositoryInterface)(nil).Create), dto)
}

// GetAllCategories mocks base method.
func (m *MockCategoriesRepositoryInterface) GetAllCategories() ([]models.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCategories")
	ret0, _ := ret[0].([]models.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCategories indicates an expected call of GetAllCategories.
func (mr *MockCategoriesRepositoryInterfaceMockRecorder) GetAllCategories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCategories", reflect.TypeOf((*MockCategoriesRepositoryInterface)(nil).GetAllCategories))
}
