// Code generated by MockGen. DO NOT EDIT.
// Source: products_repository.go
//
// Generated by this command:
//
//	mockgen -source=products_repository.go -destination=mocks/products_repository_mock.go -package=models_mocks
//

// Package models_mocks is a generated GoMock package.
package models_mocks

import (
	reflect "reflect"

	models "github.com/mytheresa/go-hiring-challenge/models"
	gomock "go.uber.org/mock/gomock"
)

// MockProductsRepositoryInterface is a mock of ProductsRepositoryInterface interface.
type MockProductsRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProductsRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockProductsRepositoryInterfaceMockRecorder is the mock recorder for MockProductsRepositoryInterface.
type MockProductsRepositoryInterfaceMockRecorder struct {
	mock *MockProductsRepositoryInterface
}

// NewMockProductsRepositoryInterface creates a new mock instance.
func NewMockProductsRepositoryInterface(ctrl *gomock.Controller) *MockProductsRepositoryInterface {
	mock := &MockProductsRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockProductsRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductsRepositoryInterface) EXPECT() *MockProductsRepositoryInterfaceMockRecorder {
	return m.recorder
}

// GetAllProducts mocks base method.
func (m *MockProductsRepositoryInterface) GetAllProducts(filters models.ProductFilters) ([]models.Product, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts", filters)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockProductsRepositoryInterfaceMockRecorder) GetAllProducts(filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockProductsRepositoryInterface)(nil).GetAllProducts), filters)
}

// GetProductDetails mocks base method.
func (m *MockProductsRepositoryInterface) GetProductDetails(productCode string) (models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductDetails", productCode)
	ret0, _ := ret[0].(models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductDetails indicates an expected call of GetProductDetails.
func (mr *MockProductsRepositoryInterfaceMockRecorder) GetProductDetails(productCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductDetails", reflect.TypeOf((*MockProductsRepositoryInterface)(nil).GetProductDetails), productCode)
}
